[package]
name = "music-rust"
version = "0.3.1"
edition = "2024"
authors = ["iapizarro"]
description = "Nord-themed Terminal Music Player written in Rust"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
rodio = { version = "0.20", features = ["symphonia-all"] }
clap = { version = "4.5", features = ["derive"] }

color-eyre = "0.6"
lofty = "0.21"
souvlaki = { version = "0.8.3", default-features = false, features = ["use_zbus"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
